### ISSUE TITLE
突然工作流被禁用，只跑了这个库和另一个百度贴吧的签到，请问各位有办法解决么

### ISSUE THREAD

**Issue by openwrt-try** [wuzhi03/MyActions#1]
今天一直无法自动同步，下午就被禁用了，
上来看才发现原库没了，关键是我的工作流也被禁用了，哪位指点一下呀，谢谢啦
Actions are currently disabled for your account. Please reach out to GitHub Support for assistance.

话说不是不让fork么，怎么还有几十号人不自觉，晕呀

**Comment by recycle007** [comment]
我看了下用那个库的基本全被禁了

**Comment by wuzhi03** [comment]
docker才是最终的归宿
