### ISSUE TITLE
整点、半点红包雨需去除GITHUB限制

### ISSUE THREAD

**Issue by saplace1** [wuzhi03/MyActions#31]
RT
 if (JSON.stringify(process.env).indexOf('GITHUB') > -1) process.exit(0)
现在整点和半点红包雨多了一条GITHUB限制，麻烦去除一下，不然每次都要重新编辑，谢谢大佬！

**Comment by wangpaixiaokai1991** [comment]
看了下龙珠的代码，确实是这条限制了GitHub的Actions.同求大佬去除。

**Comment by wuzhi03** [comment]
明白了
