### ISSUE TITLE
美丽研究院API请求失败

### ISSUE THREAD

**Issue by ABBCzar** [wuzhi03/MyActions#35]
"Response code 493 (undefined)"
美丽研究院 API请求失败，请检查网路重试

提示：请尝试换服务器ip或者设置"xinruimz-isv.isvjcloud.com"域名直连，或者自定义UA再次尝试(环境变量JD_USER_AGENT)

**Comment by wuzhi03** [comment]
请尝试换服务器ip或者设置"xinruimz-isv.isvjcloud.com"域名直连，或者自定义UA再次尝试(环境变量JD_USER_AGENT)
