### ISSUE TITLE
老哥,红包雨不行了

### ISSUE THREAD

**Issue by shenmadouyaowen** [wuzhi03/MyActions#36]
老哥,红包雨不行了,快更新回来

**Comment by 1668458964** [comment]
老大，红包雨没了啊，我见其他人有雨的

**Comment by shenmadouyaowen** [comment]
> 老大，红包雨没了啊，我见其他人有雨的

去原创作者那里拿代码替换回来就可以了

**Comment by 1668458964** [comment]
👌🏻

**Comment by 1668458964** [comment]
> > 老大，红包雨没了啊，我见其他人有雨的
> 
> 去原创作者那里拿代码替换回来就可以了

👌🏻

**Comment by 1668458964** [comment]
> > 老大，红包雨没了啊，我见其他人有雨的
> 
> 去原创作者那里拿代码替换回来就可以了

大佬，能否指点下怎么替换啊，有偿也行

**Comment by kongren978** [comment]
原

> > 老大，红包雨没了啊，我见其他人有雨的
> 
> 去原创作者那里拿代码替换回来就可以了



> > 老大，红包雨没了啊，我见其他人有雨的
> 
> 去原创作者那里拿代码替换回来就可以了

原作者能否给个地址

**Comment by cmwz2018** [comment]
红包雨有啊

**Comment by shenmadouyaowen** [comment]
> 原
> 
> > > 老大，红包雨没了啊，我见其他人有雨的
> > 
> > 
> > 去原创作者那里拿代码替换回来就可以了
> 
> > > 老大，红包雨没了啊，我见其他人有雨的
> > 
> > 
> > 去原创作者那里拿代码替换回来就可以了
> 
> 原作者能否给个地址

地址是:[nianyuguai/longzhuzhu](https://github.com/nianyuguai/longzhuzhu),但是git的好像不行
