### ISSUE TITLE
宠汪汪赛跑助力

### ISSUE THREAD

**Issue by xiaorizi01** [wuzhi03/MyActions#46]
仓库里怎么没有宠汪汪赛跑助力脚本了呢，可不可以添加进去呢😀😀

**Comment by wuzhi03** [comment]
看一下会加

**Comment by xiaorizi01** [comment]
谢谢大佬



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wuzhi03 ***@***.***&gt;
发送时间: 2021年5月21日 14:33
收件人: wuzhi03/MyActions ***@***.***&gt;
抄送: xiaorizi01 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[wuzhi03/MyActions] 宠汪汪赛跑助力 (#46)





 
看一下会加
