### ISSUE TITLE
京东“坐等更新”活动能否追加

### ISSUE THREAD

**Issue by anakinlee99** [wuzhi03/MyActions#51]
大佬，请问京东有个“坐等更新”的活动，也可以获得京豆。
京豆首页搜索“坐等更新”，浮窗有瓜分千万京豆的活动，可进入。

和尚大佬好像已经更新了js文件，请问能否追加。
https://github.com/monk-coder/dust/tree/dust/normal/adolf_urge.js

**Comment by wuzhi03** [comment]
不忙的时候会
