### ISSUE TITLE
pushplus推送重复推送

### ISSUE THREAD

**Issue by LeanFly** [wuzhi03/MyActions#53]
Hi，大佬好，最近pushplus出现了重复推送的情况，每个通知都推两次……^-^

**Comment by wuzhi03** [comment]
暂未发现此情况，检查自己的容器吧，或者具体什么脚本的通知会通知两次

**Comment by LeanFly** [comment]
> 暂未发现此情况，检查自己的容器吧，或者具体什么脚本的通知会通知两次

理了一下：
    前几天群晖docker异常停止并自动重启，面板服务没起来，手动执行node server.js启动了面板；
    每个脚本的通知都会收到双份；
刚才手动关闭并重启了容器，面板起不来，使用pm2 启动了面板，目前没出现收到重复通知的情况。
