### ISSUE TITLE
导出互助码脚本格式化

### ISSUE THREAD

**Issue by kkkevin07** [wuzhi03/MyActions#54]
我自己用java写了一个示例代码，希望能给导出互助码提供一些帮助

> final ArrayList<String> strings = new ArrayList<>();
strings.add("1");
strings.add("2");
strings.add("3");
String key = "MyFruit";
for (int i = 0; i < strings.size(); i++) {
    System.out.println(key + (i + 1) + "=\"" + strings.get(i) + "\"");
}
String helpKey = "ForOtherFruit";
for (int i = 0; i < strings.size(); i++) {
    StringBuilder help = new StringBuilder(helpKey + (i + 1) + "=\"");
    for (int j = 0; j < strings.size(); j++) {
        if (!(j == 0 || (i == j - 1 && j == i + 1) || (i == strings.size() - 1 && j == strings.size() - 1))) {
            help.append("@");
        }
        if (j != i) {
            help.append("${").append(key).append(j + 1).append("}");
        }
    }
    help.append("\"");
    System.out.println(help);
}

结果

> MyFruit1="abc"
MyFruit2="efg"
MyFruit3="hij"
ForOtherFruit1="${MyFruit2}@${MyFruit3}"
ForOtherFruit2="${MyFruit1}@${MyFruit3}"
ForOtherFruit3="${MyFruit1}@${MyFruit2}"`

**Comment by wuzhi03** [comment]
互助码格式化暂时无精力安排
