### ISSUE TITLE
京喜工厂开团助力已经失效

### ISSUE THREAD

**Issue by tianchixia** [wuzhi03/MyActions#55]
京喜工厂开团助力已经好几天失效了。

**Comment by wuzhi03** [comment]
更换新的开团ID

**Comment by tianchixia** [comment]
你好，新的开团ID，你在更新说明中，说可以自行抓包替换，我没有试过，请问你是在手机上抓包还是电脑上？苹果手机用的是什么软件？谢谢😊

wuzhi03 ***@***.***>于2021年5月27日 周四00:56写道：
