### ISSUE TITLE
使用pushplus推送出现的BUG

### ISSUE THREAD

**Issue by untiluuu** [wuzhi03/MyActions#58]
![image](https://user-images.githubusercontent.com/61788028/119668694-fa975f80-be69-11eb-9ed4-f8993c10a435.png)
![image](https://user-images.githubusercontent.com/61788028/119668989-3cc0a100-be6a-11eb-93c4-37d508b3a3e8.png)

使用使用pushplus推送时，日志显示COOKIE正常，但推送时确报已失效

**Comment by wuzhi03** [comment]
正在寻找原因
