### ISSUE TITLE
京东赚赚代码执行报错

### ISSUE THREAD

**Issue by xiaoxintang** [wuzhi03/MyActions#6]
第一个报错
![image](https://user-images.githubusercontent.com/24927686/114506278-22d55100-9c64-11eb-8ec9-ba43b1bda79e.png)
第二个报错
![image](https://user-images.githubusercontent.com/24927686/114506459-63cd6580-9c64-11eb-9de0-5b24f586c2b7.png)

**Comment by wuzhi03** [comment]
修好了同步就可以了
