### ISSUE TITLE
互助码每次填写挺麻烦的能否自动获取后根据规则自动互助呢？

### ISSUE THREAD

**Issue by lzqd** [wuzhi03/MyActions#69]
互助码每次填写挺麻烦的能否自动获取后根据互助码使用规则自动互助呢？
这样配置文件基本不重新配置也能适用更新

**Comment by wuzhi03** [comment]
大部分互助码不会变，而且有很多脚本是内部账户循环互助，而且不同人的需求不一样，有些需要指定互助码互助
