### ISSUE TITLE
财富岛已失效

### ISSUE THREAD

**Issue by tianchixia** [wuzhi03/MyActions#71]
![image](https://user-images.githubusercontent.com/71068929/120171091-3a789100-c234-11eb-84c3-8f9865722262.png)

**Comment by wuzhi03** [comment]
换新的了

**Comment by tianchixia** [comment]
你好，更新后财富岛还是不能正常招工，看日志，那个互助码也没有获取到，麻烦你再看看问题出在哪🙏🏻

wuzhi03 ***@***.***>于2021年6月1日 周二00:27写道：

**Comment by tianchixia** [comment]
你好，刚刚又看了一下，招工目前是可以正常招了，那个出海寻宝不能正常运作🙏🏻

chixia Tian ***@***.***>于2021年6月1日 周二09:13写道：
