### ISSUE TITLE
财富岛依旧有问题

### ISSUE THREAD

**Issue by wangyunqing198801** [wuzhi03/MyActions#75]
🔔京喜财富岛, 开始!
您的cookie选择的是用&隔开

====================共有3个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/6/2 上午11:51:06=====================

开始获取京喜财富岛配置文件

您提供了0个账号的京喜财富岛助力码

开始【京东账号1】XXX

由于您第1个京东账号未提供shareCode,将采纳本脚本自带的助力码

开始
"getaddrinfo ENOTFOUND share.turinglabs.net"
京喜财富岛 API请求失败，请检查网路重试
第1个京东账号将要助力的好友["F45CB4F07997DFE748E5656521A9034446A1568F6950206B0D44A5664662275D"]

获取用户信息：您操作过于频繁, 请稍后重试

当前等级:undefined,财富值:undefined

财富岛好友互助码每次运行都变化,旧的可继续使用

【京东账号1（XXXX）的京喜财富岛好友互助码】undefined

签到列表：success

📌签到：您操作过于频繁, 请稍后重试，获得财富 ¥ 0

待开通场景ID列表sceneList;["1001","1002","1003"]

获取【📆日常任务】列表 ，总共6个任务！

开始第1个【📆日常任务】：每日三餐上岛

每日三餐上岛【做日常任务】：任务进行中或者未到任务时间

每日三餐上岛【领日常奖励】：任务为成就任务或者未到任务时间

结束第1个【📆日常任务】：每日三餐上岛

开始第2个【📆日常任务】：每日三餐上岛

每日三餐上岛【做日常任务】：任务进行中或者未到任务时间

每日三餐上岛【领日常奖励】：任务为成就任务或者未到任务时间

结束第2个【📆日常任务】：每日三餐上岛

开始第3个【📆日常任务】：每日三餐上岛

**Comment by wuzhi03** [comment]
没办法，最新版就是这个
