### ISSUE TITLE
API请求失败问题

### ISSUE THREAD

**Issue by anakinlee99** [wuzhi03/MyActions#76]
请问大佬，使用你的库运行的时候会不会连接到GitHub网站读取数据。
我这边很多任务都出现了”API查询请求失败“的错误，怀疑是不是Github网站访问不畅导致的。
请大佬帮忙看一下，非常感谢！

部分错误log如下：

种豆得豆: API查询请求失败 ‼️‼️
function_id:collectUserNutr

❗️京东种豆得豆, 错误!

偷取好友营养液情况:undefined
可以偷的好友的信息paradiseUuid::"x4dqarrfw22un5mg5qn24np5ijbdurbeulawwsi"
开始偷好友
偷取好友营养液情况:{"code":"0","data":{"collectResult":"2","collectMsg":"暂无营养液可收取，等会再来吧","timeNutrientsRes":{"state":"3","countDown":"10779","bottleState":"1","nextReceiveTime":"1622624389000","nutrCount":"0","nutrCountLimit":"3","endTimeNutrCount":"3"}}}
偷取好友营养液成功

种豆得豆: API查询请求失败 ‼️‼️
function_id:plantBeanIndex

❗️京东种豆得豆, 错误!

plantBeanIndexResult:undefined
【上轮京豆】已领取

种豆得豆: API查询请求失败 ‼️‼️
function_id:plantBeanIndex

❗️京东种豆得豆, 错误!

(node:12636) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at /jd/scripts/jd_plantBean.js:381:41
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by wuzhi03** [comment]
会，但是大部分都是cdn加速之后的github
