### ISSUE TITLE
DD农场

### ISSUE THREAD

**Issue by dmmmmd888** [wuzhi03/MyActions#90]
删除好友删的一个都不剩了，连给好友浇水都弄不了了，本地删除部分代码，还是会删除好友，请问该怎么办呢？

**Comment by srwgin** [comment]
现在逻辑是删除全部好友再从助理码第一个人开始加，不过好像就加3个人
如果你自己有固定需要助力的人的话，那前三个人码是固定的
如果他们不用脚本，那你就已经是好友了，所以前三人失败了
要改代码的话 有2点
1.检查自己好友列表至少留下两个人用来完成浇水任务，剩下的好友可以删除
2.自动加好友时候 能不能跳过自定义的人，而从随机添加的人中加，可以的话不要只加3个加10-15个

**Comment by srwgin** [comment]
也许还要重新抓包看下现在的邀请好友和接受邀请的请求和以前有什么不同

**Comment by dmmmmd888** [comment]
好的好的，明白了！我去抓包看下，可以关了！

**Comment by srwgin** [comment]
还有奇怪的地方就是
现在微信小程序是不能分享助力和添加好友的并且显示在升级让你使用官方app分享，而且当你在官方app看好友列表时候，右边那个好友动态看下，你会发现以前脚本自动加的那些人动态也在，但是点了之后看不到他们的农场了，估计又是哪里做了手脚
