### ISSUE TITLE
翻翻乐脚本更新了

### ISSUE THREAD

**Issue by qxshawn** [wuzhi03/MyActions#91]
翻翻乐脚本更新，现在默认3次，麻烦大佬更新下
https://github.com/Wenmoux/scripts/commit/56cce78d1f79a7659723c3c90c2a6e19a8616918#diff-3353dd66fd1715f2c85edbd377a309a2e069bf2028d6d7e596f98cd5c2f3607e

**Comment by wuzhi03** [comment]
已加入，感谢提供地址
