### ISSUE TITLE
希望大佬脚本更新一下 有大部分脚本长时间没更新

### ISSUE THREAD

**Issue by Fcatme** [wuzhi03/MyActions#94]
大佬有部分脚本已经很久没更新了 希望更新一下~ 谢谢了
https://github.com/chinnkarahoi/jd_scripts
在这个仓库看到好多脚本都备注更新时间都比较新

**Comment by wuzhi03** [comment]
更新与否取决于脚本能不能用，而不是刻意去更改最近更新时间

**Comment by Fcatme** [comment]
脚本有部分是失效 会报错信息 导致没办法正常运作
比如 京喜农场
![image](https://user-images.githubusercontent.com/33803252/120920708-c128e480-c6f2-11eb-8a06-7613e121d5f9.png)
用上面的仓库脚本覆盖了一下 然后重新执行就恢复了
![image](https://user-images.githubusercontent.com/33803252/120920747-f1708300-c6f2-11eb-8a2c-24e5af47afe9.png)
